name: Danger Checks
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
         # bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Danger Checks
        run: |
          gem install faraday-retry
          gem install bundler
          bundle install
          bundle exec danger

        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}